# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 19:49
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import autoslug.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('mini', models.DecimalField(decimal_places=2, max_digits=8)),
                ('clos', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxi', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mini', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cup.Cup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='don',
            unique_together=set([('cup', 'user')]),
        ),
    ]
