# Generated by Django 2.0.1 on 2018-01-06 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='don',
            name='cup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cup.Cup'),
        ),
        migrations.AlterField(
            model_name='don',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
